### ISSUE TITLE
处理大量数据时候，写的速度慢的话，会造成大量内存的使用

### ISSUE THREAD

**Issue by liangyali** [topdmc/ElasticsearchStreamIndex#2]
建议修改意见：

sourceStream => transformStream => ESStream 通过pipe的方式进行调用，这样可以起到流量控制的作用，使用pipe后，如果超过higtWaterMark后会暂停流，当低于highWaterMark后会resume继续进行。

sourceStream : 可以为文件流或其他流

**Comment by fanweixiao** [comment]
先去掉直接invoke的调用方式，在`v2.0.0`版里切换成`TransformStream`
